/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRunsRouteImport } from './routes/dashboard/runs'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardRunsRunIdRouteImport } from './routes/dashboard/runs/$runId'
import { Route as DashboardRunsRunIdReportRouteImport } from './routes/dashboard/runs/$runId.report'
import { Route as DashboardProjectsProjectIdRunsRouteImport } from './routes/dashboard/projects/$projectId.runs'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRunsRoute = DashboardRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRunsRunIdRoute = DashboardRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => DashboardRunsRoute,
} as any)
const DashboardRunsRunIdReportRoute =
  DashboardRunsRunIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => DashboardRunsRunIdRoute,
  } as any)
const DashboardProjectsProjectIdRunsRoute =
  DashboardProjectsProjectIdRunsRouteImport.update({
    id: '/$projectId/runs',
    path: '/$projectId/runs',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/safety': typeof SafetyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/runs': typeof DashboardRunsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRouteWithChildren
  '/dashboard/projects/$projectId/runs': typeof DashboardProjectsProjectIdRunsRoute
  '/dashboard/runs/$runId/report': typeof DashboardRunsRunIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/safety': typeof SafetyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/runs': typeof DashboardRunsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRouteWithChildren
  '/dashboard/projects/$projectId/runs': typeof DashboardProjectsProjectIdRunsRoute
  '/dashboard/runs/$runId/report': typeof DashboardRunsRunIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/safety': typeof SafetyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/runs': typeof DashboardRunsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/runs/$runId': typeof DashboardRunsRunIdRouteWithChildren
  '/dashboard/projects/$projectId/runs': typeof DashboardProjectsProjectIdRunsRoute
  '/dashboard/runs/$runId/report': typeof DashboardRunsRunIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/safety'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/workflow'
    | '/dashboard/projects'
    | '/dashboard/runs'
    | '/dashboard/settings'
    | '/dashboard/runs/$runId'
    | '/dashboard/projects/$projectId/runs'
    | '/dashboard/runs/$runId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/safety'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/workflow'
    | '/dashboard/projects'
    | '/dashboard/runs'
    | '/dashboard/settings'
    | '/dashboard/runs/$runId'
    | '/dashboard/projects/$projectId/runs'
    | '/dashboard/runs/$runId/report'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/safety'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/workflow'
    | '/dashboard/projects'
    | '/dashboard/runs'
    | '/dashboard/settings'
    | '/dashboard/runs/$runId'
    | '/dashboard/projects/$projectId/runs'
    | '/dashboard/runs/$runId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  SafetyRoute: typeof SafetyRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs': {
      id: '/dashboard/runs'
      path: '/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof DashboardRunsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs/$runId': {
      id: '/dashboard/runs/$runId'
      path: '/$runId'
      fullPath: '/dashboard/runs/$runId'
      preLoaderRoute: typeof DashboardRunsRunIdRouteImport
      parentRoute: typeof DashboardRunsRoute
    }
    '/dashboard/runs/$runId/report': {
      id: '/dashboard/runs/$runId/report'
      path: '/report'
      fullPath: '/dashboard/runs/$runId/report'
      preLoaderRoute: typeof DashboardRunsRunIdReportRouteImport
      parentRoute: typeof DashboardRunsRunIdRoute
    }
    '/dashboard/projects/$projectId/runs': {
      id: '/dashboard/projects/$projectId/runs'
      path: '/$projectId/runs'
      fullPath: '/dashboard/projects/$projectId/runs'
      preLoaderRoute: typeof DashboardProjectsProjectIdRunsRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
  }
}

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRunsRoute: typeof DashboardProjectsProjectIdRunsRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRunsRoute: DashboardProjectsProjectIdRunsRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRunsRunIdRouteChildren {
  DashboardRunsRunIdReportRoute: typeof DashboardRunsRunIdReportRoute
}

const DashboardRunsRunIdRouteChildren: DashboardRunsRunIdRouteChildren = {
  DashboardRunsRunIdReportRoute: DashboardRunsRunIdReportRoute,
}

const DashboardRunsRunIdRouteWithChildren =
  DashboardRunsRunIdRoute._addFileChildren(DashboardRunsRunIdRouteChildren)

interface DashboardRunsRouteChildren {
  DashboardRunsRunIdRoute: typeof DashboardRunsRunIdRouteWithChildren
}

const DashboardRunsRouteChildren: DashboardRunsRouteChildren = {
  DashboardRunsRunIdRoute: DashboardRunsRunIdRouteWithChildren,
}

const DashboardRunsRouteWithChildren = DashboardRunsRoute._addFileChildren(
  DashboardRunsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardRunsRoute: typeof DashboardRunsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardRunsRoute: DashboardRunsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  SafetyRoute: SafetyRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
